export const CREATE_BOOK = 'CREATE_BOOK'
export const BOOK_CREATED_SUCCESS = 'BOOK_CREATED_SUCCESS'
export const BOOK_CREATED_FAIL = 'BOOK_CREATED_FAIL'

export const FETCH_BOOK = 'FETCH_BOOK'
export const BOOK_FETCH_SUCCESS = 'BOOK_FETCH_SUCCESS'
export const BOOK_FETCH_FAIL = 'BOOK_FETCH_FAIL'


export const USER_REGISTER = 'USER_REGISTER'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'


export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'

export const SEARCH_BOOK = 'SEARCH_BOOK'
export const BOOK_SEARCH_SUCCESS = 'BOOK_SEARCH_SUCCESS'
export const BOOK_SEARCH_FAIL = 'BOOK_SEARCH_FAIL'
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'