export const CREATE_BOOK = 'CREATE_BOOK'
export const BOOK_CREATED_SUCCESS = 'BOOK_CREATED_SUCCESS'
export const BOOK_CREATED_FAIL = 'BOOK_CREATED_FAIL'

export const FETCH_BOOK = 'FETCH_BOOK'
export const BOOK_FETCH_SUCCESS = 'BOOK_FETCH_SUCCESS'
export const BOOK_FETCH_FAIL = 'BOOK_FETCH_FAIL'


export const USER_REGISTER = 'USER_REGISTER'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'


export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'

export const SEARCH_BOOK = 'SEARCH_BOOK'
export const BOOK_SEARCH_SUCCESS = 'BOOK_SEARCH_SUCCESS'
export const BOOK_SEARCH_FAIL = 'BOOK_SEARCH_FAIL'
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'

export const CREATE_POST = 'CREATE_POST'
export const FETCH_POSTS = 'FETCH_POSTS'

export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'



export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST'

export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS'
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_fail'



export const UPDATE_BOOK_REQUEST = 'UPDATE_BOOK_REQUEST';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';

export const FETCH_SINGLE_BOOK_REQUEST = 'FETCH_SINGLE_BOOK_REQUEST';
export const FETCH_SINGLE_BOOK_SUCCESS = 'FETCH_SINGLE_BOOK_SUCCESS';
export const FETCH_SINGLE_BOOK_FAILURE = 'FETCH_SINGLE_BOOK_FAILURE';

export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';
export const  FETCH_AUTHORS_REQUEST='FETCH_AUTHORS_REQUEST'




export const DELETE_AUTHOR_REQUEST = 'DELETE_AUTHOR_REQUEST';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_FAILURE = 'DELETE_AUTHOR_FAILURE';


export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
export const UPDATE_AUTHOR_FAILURE = 'UPDATE_AUTHOR_FAILURE';
